# Generated by Django 3.2.7 on 2021-11-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30, verbose_name='Producto')),
                ('productType', models.IntegerField(choices=[(1, 'Dama'), (2, 'Caballero'), (3, 'Niño'), (4, 'Niña')], default=1, verbose_name='Categoria')),
                ('productPrice', models.FloatField(default=0.0, verbose_name='Precio')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('productImg', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
