# Generated by Django 3.2.7 on 2021-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCant',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
