# Generated by Django 3.2.7 on 2021-11-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_product_productcant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productCant',
            new_name='productAmount',
        ),
    ]
